### ISSUE TITLE
Cannot install self built, unsigned version

### ISSUE THREAD

**Issue by ThatOneCalculator** [ouchadam/small-talk#133]
![Screenshot_20220908-120442.png](https://user-images.githubusercontent.com/44733677/189205467-0e696754-fdc6-4d45-934a-7dfa3b1cc96b.png)

**Comment by ouchadam** [comment]
This is likely due to generating an unsigned build, by default the build script will generate an APK using a debug key when the -Punsigned is omitted

The unsigned flag is mainly used for generating the artifact and self signing which is the usual fdroid process 

I should clarify better in the readme, sorry about that!
