### ISSUE TITLE
general user experience notes

### ISSUE THREAD

**Issue by mi5o** [ouchadam/small-talk#152]
Knowing that this is "bare-bones" application with "more functions to come," I am not going to complain about each limitation in a separate issue. Rather, I aim to create of list of bumps I encountered. Maybe some of them were not known to the developer yet, and maybe some will inspire the developer to provide a fix. I am skipping obvious limitations like no A/V chat, no attachment sending, no geo-location sharing, etc.

I'd like to stress that I truly appreciate the size of the application (compared to the reference implementation of Matrix client that is a real memory hog and it only eats more and more as it runs — right now, Element eats 812 MB of my RAM while ST only 105 MB, Elements occupies 187 MB of my disk, which is only app, not data, while ST occupies only 16 MB), _it is already usable_ as it is now, wow! I fully understand compromises needed among time needed for FOSS development, application memory requirements, and available application features. I am the user who is ready to sacrifice many features, particularly those which are seldom used and can wait until they are achieved via web client.

Here is the list:

- session identification
  - application properly generates, but does not reveal its **device ID** (unless you peek into internal data, where both device ID and access token are stored in plain text), thus not easy to identify in other clients, which session I want to mark as trusted or share room keys;
  - application does not allow to provide custom **device (session) name**, which is fine, but it does not provide the default one (like the app name), with the same consequence as above;
- message history and encryption
  - for each room, only a few **recent messages** are displayed, which is okay for initial view, but it seems there is no way to trigger downloading more of them;
  - rooms without encryption show the messages as expected, but rooms with encryption give mixed results: some messages are decrypted, some messages are **not decrypted** (I see no pattern in it);
- non plain-text messages
  - **HTML formatted** messages are displayed in raw text, with some (!) tags -- I think for bare-bones app this could be okay, except that the tags are shown (or not shown) uniformly, but in general I would suggest to handle at least blockquote tag, since it is frequently used by other clients for quoting the part of the message the reply goes to;
  - **unsupported** message types are either confusingly displayed as "Encrypted message" (like poll) or not displayed at all (like a shared geo-location) -- I think some more explanatory placeholder should be displayed and for bare-bones app this should be good enough;
  - **links** in messages are neither highlighted nor clickable -- which could probably be good enough for bare-bones app, but then I think at least long-press on a message should copy its whole content into the clipboard;
- message events
  - **edited** messages are displayed in their latest version and properly identified as edited (next to time-stamp), but there is also confusingly added leading asterisk symbol to such messages;
  - **deleted** messages are still seen, unchanged;
- user interface
  - there is a **Setting** menu item in each room, but currently it does nothing;
  - while menus and room names are okay, following the global system settings, the messages themselves have unusually **wide letter spacing**;
  - the application comes with pre-defined colours without any option to customise, which is fine, but it does not fully adhere to the system settings at OS level -- I have complete dark (AMOLED) theme with white letters and blue colour for highlighting, while the application matches only the dark theme with white letters, and uses dark-grey and pink bubbles in each room;
- code inspection
  - application apparently includes all system-native libs from Element client, many of which do not seem to be used (e.g. mapbox, jingle, opus, realm, react);
  - libraries (like Fabric), which prevent application from being included in main F-Droid repository, and which are not necessary for bare-bones app, thus hopefully could be easily plugged out for F-Droid builds.

(valid for beta version labelled as 19/09/2022-V1)

**Comment by ouchadam** [comment]
thanks for the detailed information! 

`SmallTalk` is currently very _work in progress_ but I would argue barebones should never mean a broken, unexpected or painful experience, like many of your points mention

### Session identification
> application properly generates, but does not reveal its device ID (unless you peek into internal data, where both device ID and access token are stored in plain text), thus not easy to identify in other clients, which session I want to mark as trusted or share room keys;

:+1:  I plan to provide a way to view encryption, verification and device status.
On device security isn't currently a goal of `SmallTalk` but I will aim to make this clearer, especially mentioning the data is in plain text 

> application does not allow to provide custom device (session) name, which is fine, but it does not provide the default one (like the app name), with the same consequence as above;

will fix :+1: 

### Message history and encryption
> for each room, only a few recent messages are displayed, which is okay for initial view, but it seems there is no way to trigger downloading more of them;

Message history is currently a missing feature and is a _must have_ for a public non beta release.

> rooms without encryption show the messages as expected, but rooms with encryption give mixed results: some messages are decrypted, some messages are not decrypted (I see no pattern in it);

Currently `SmallTalk` is only able to decrypt messages it has received keys for either by importing room keys or by capturing keys as part of the sync response, this means if the device is offline and misses a sync it's possible for those keys to be lost.

Other matrix clients make up for this by supporting Cross signing combined with Key Forwarding, to allow other sessions to share their keys to decrypt the messages.

However, the encryption/decryption part of the flow is one of the largest complexities within the app and I wouldn't be surprised if there are bugs separate from key forwarding, I'll investigate :+1:   

#### non plain-text messages
> HTML formatted messages are displayed in raw text, with some (!) tags -- I think for bare-bones app this could be okay, except that the tags are shown (or not shown) uniformly, but in general I would suggest to handle at least blockquote tag, since it is frequently used by other clients for quoting the part of the message the reply goes to;

Agreed, will do :+1: 

> unsupported message types are either confusingly displayed as "Encrypted message" (like poll) or not displayed at all (like a shared geo-location) -- I think some more explanatory placeholder should be displayed and for bare-bones app this should be good enough;

Agreed :+1:  eventually I believe the app should support all possible message types to be able to correctly interact within the matrix ecosystem, although it's not a priority to add them just yet 

> links in messages are neither highlighted nor clickable -- which could probably be good enough for bare-bones app, but then I think at least long-press on a message should copy its whole content into the clipboard;

Definitely an oversight, will address :+1: 


### message events
>edited messages are displayed in their latest version and properly identified as edited (next to time-stamp), but there is also confusingly added leading asterisk symbol to such messages;

This might be due to not having the original message as currently the app expects to the find the original message (which it might not have as the history isn't fetched), will investigate!

>deleted messages are still seen, unchanged;

Will address, is a must have for a public non beta release

### user interface
> there is a Setting menu item in each room, but currently it does nothing;

:+1:  will remove until the page is built

>while menus and room names are okay, following the global system settings, the messages themselves have unusually wide letter spacing;

Will investigate :+1: 

>the application comes with pre-defined colours without any option to customise, which is fine, but it does not fully adhere to the system settings at OS level -- I have complete dark (AMOLED) theme with white letters and blue colour for highlighting, while the application matches only the dark theme with white letters, and uses dark-grey and pink bubbles in each room;

Interesting, I'll need to investigate fully dark themes investigate more :+1: 

### code inspection
>application apparently includes all system-native libs from Element client, many of which do not seem to be used (e.g. mapbox, jingle, opus, realm, react);

Currently `SmallTalk` only uses the [Olm](https://gitlab.matrix.org/matrix-org/olm) native library, everything else to do with interacting with a homeserver has been built from the ground up.

>libraries (like Fabric), which prevent application from being included in main F-Droid repository, and which are not necessary for bare-bones app, thus hopefully could be easily plugged out for F-Droid builds.

This has been addressed by https://github.com/ouchadam/small-talk/pull/105 by introducing a build flag to replace the `firebase crashlytics` and `firebase push messaging` dependencies with empty variants, which has meant the app is now available on [IzzySoft's fdroid repo](https://apt.izzysoft.de/fdroid/index/apk/app.dapk.st) 

----

I hope that covered everything! I'll start to extract separate issues for the points you've made

**Comment by ouchadam** [comment]
- [x] Deleted messages 
- [x] Better device display name
- [x] Removed room settings option which does nothing

TODO 

- [ ] Fix edit behaviour 
- [ ] Remove html tags from messages
- [ ] Allow copying messages
- [ ] Make links clickable

**Comment by ouchadam** [comment]
all tasks complete! edits, link clicking and html tags have been fixed by https://github.com/ouchadam/small-talk/pull/224
